version: "3.8"
services:
  prometheus:
    image: prom/prometheus:v2.43.0
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - ../prometheus.yml:/etc/prometheus/prometheus.yml

  micrometer:
    image: monitoring-demo/micrometer-example:0.0.1-SNAPSHOT
    container_name: micrometer
    ports:
      - 8080:8080